# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: banders2  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  org: raniotitonk # Orginization
  imageName: tobintaxer # Replace with the name of the image you want to publish

steps:
- script: |
    docker build -f TobinTaxer/Dockerfile -t $(org)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(org)/$(imageName)
  #env:
  #  pswd: $(dockerPassword)        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface
  displayName: 'docker build, login and push'
