apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tobintaxer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tobintaxer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tobintaxer
        image: raniotitonk/tobintaxer
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
---
apiVersion: v1
kind: Service
metadata:
  name: tobintaxer
spec:
  selector:
    app: tobintaxer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP